model:
  name: mnist_cvae
  architecture: mnist/CVAE
  options:
    hyperparameters:
      batch_size: 1
      learning_rate: 0.0001
      latent_dim: 32
      hidden_dims: [32, 64, 128, 256, 512]
      # image_dims: [512, 640, 1]  # Get this from `spec` instead
    data:
      files:
        train: data/mnist/train/
        val: data/mnist/val/
        test: data/mnist/test/
      image:
        dims: [28, 28, 1]
---
trainer:
  max_epochs: 100
  gpus: [0]
  fast_dev_run: true
  log_gpu_memory: true
  track_grad_norm: 2
---
loggers:
  TestTubeLogger:
    save_dir: experiments/
