language: python
os: linux
dist: bionic

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  pip: false

before_install:
  - sudo apt update
  - sudo apt install libsndfile1
  # Install anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda
  # Create conda environment
  - conda create -q -n environment python=$TRAVIS_PYTHON_VERSION
  - conda activate environment

install:
  - conda install pytorch torchvision cpuonly -c pytorch
  - pip install pytorch-lightning
  - pip install -e .[dev]

script:
  - pytest

after_script:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change
