system:
  architecture: CVAE2d
  hyperparameters:
    latent_dim: 4096
    module_repeat: 2
    use_inception: false
    batch_size: 2
    image_dims: [512, 640, 1]
  name: CVAE2d
---
files:
  root: .
  train_dir: data/train
  val_dir: data/val
  test_dir: data/test
  log_dir: logs
  model_dir: models/
---
train:
  epochs: 100
  learning_rate: 0.0001  # 1e-4
  gpus: [0]
---
audio:
  duration: null
  offset: 0.0
  sample_rate: 32768
  resample_type: kaiser_fast
  format: wav
---
spectrogram:
  n_fft: 4096
  hop_length: 256
  n_mels: 512
  n_frames: 640
  truncate: true
  flip: true
  top_db: 80
