model:
  latent_dim: 4096
  module_repeat: 2
  use_inception: false
data:
  root: .
  image_dims: [512, 640, 1]

train:
  batch_size: 1
  epochs: 1000
  learning_rate: 1e-4
  log_dir: logs
  model_dir: models/
  model_name: vae
